USE movies

/*
SELECT m.TITLE, m.YEAR, s.NAME, s.ADDRESS FROM MOVIE m
	JOIN STUDIO s ON m.PRODUCERC# = s.PRESC#
WHERE m.LENGTH > 120
*/

/*
SELECT DISTINCT m.STUDIONAME, s.STARNAME FROM MOVIE m
	JOIN STARSIN s ON m.TITLE = s.MOVIETITLE AND m.YEAR = s.MOVIEYEAR
ORDER BY m.STUDIONAME
*/

/*
SELECT DISTINCT me.NAME FROM MOVIE m
	JOIN MOVIEEXEC me ON m.PRODUCERC# = me.CERT#
	JOIN STARSIN s ON m.TITLE = s.MOVIETITLE AND m.YEAR = s.MOVIEYEAR
WHERE s.STARNAME = 'Harrison Ford'
*/

/*
SELECT DISTINCT ms.NAME FROM MOVIE m
	JOIN STARSIN s ON m.TITLE = s.MOVIETITLE AND m.YEAR = s.MOVIEYEAR
	JOIN MOVIESTAR ms ON s.STARNAME = ms.NAME
WHERE m.STUDIONAME = 'MGM' AND ms.GENDER = 'F'
*/

/*
SELECT * FROM MOVIE m
	JOIN MOVIEEXEC me ON me.CERT# = m.PRODUCERC#
WHERE m.PRODUCERC# = (SELECT PRODUCERC# FROM MOVIE WHERE TITLE = 'Star Wars' AND YEAR = 1977)
*/

/*
SELECT NAME FROM MOVIESTAR
LEFT OUTER JOIN STARSIN ON NAME = STARNAME
WHERE STARNAME IS NULL
*/